//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPBusz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buszok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buszok()
        {
            this.Utvonalak = new HashSet<Utvonalak>();
        }
    
        public int id { get; set; }
        public string nev { get; set; }
        public Nullable<double> gps_lat { get; set; }
        public Nullable<double> gps_long { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utvonalak> Utvonalak { get; set; }
    }
}
