//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPBusz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VPBUSZEntities4 : DbContext
    {
        public VPBUSZEntities4()
            : base("name=VPBUSZEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allomasok> Allomasok { get; set; }
        public virtual DbSet<Buszok> Buszok { get; set; }
        public virtual DbSet<Utvonalak> Utvonalak { get; set; }
        public virtual DbSet<Felhasznalok> Felhasznalok { get; set; }
    }
}
